export const FORM_STAGE = {
  PHONE_FORM: 'PHONE_FORM',
  DETAIL_INFO_FORM: 'DETAIL_INFO_FORM',
}

export const SIGNUP_REGISTER_BEGIN = 'SIGNUP_REGISTER_BEGIN';
export const SIGNUP_REGISTER_SUCCESS = 'SIGNUP_REGISTER_SUCCESS';
export const SIGNUP_REGISTER_FAILURE = 'SIGNUP_REGISTER_FAILURE';
export const SIGNUP_REGISTER_DISMISS_ERROR = 'SIGNUP_REGISTER_DISMISS_ERROR';
export const SIGNUP_GENERATE_VERIFY_CODE_BEGIN = 'SIGNUP_GENERATE_VERIFY_CODE_BEGIN';
export const SIGNUP_GENERATE_VERIFY_CODE_SUCCESS = 'SIGNUP_GENERATE_VERIFY_CODE_SUCCESS';
export const SIGNUP_GENERATE_VERIFY_CODE_FAILURE = 'SIGNUP_GENERATE_VERIFY_CODE_FAILURE';
export const SIGNUP_GENERATE_VERIFY_CODE_DISMISS_ERROR = 'SIGNUP_GENERATE_VERIFY_CODE_DISMISS_ERROR';
export const SIGNUP_VERIFY_CODE_BEGIN = 'SIGNUP_VERIFY_CODE_BEGIN';
export const SIGNUP_VERIFY_CODE_SUCCESS = 'SIGNUP_VERIFY_CODE_SUCCESS';
export const SIGNUP_VERIFY_CODE_FAILURE = 'SIGNUP_VERIFY_CODE_FAILURE';
export const SIGNUP_VERIFY_CODE_DISMISS_ERROR = 'SIGNUP_VERIFY_CODE_DISMISS_ERROR';
  
