export const SETTINGS_CHANGE_TO_EDIT_STATUS = 'SETTINGS_CHANGE_TO_EDIT_STATUS';
export const SETTINGS_SAVE_USER_INFO_BEGIN = 'SETTINGS_SAVE_USER_INFO_BEGIN';
export const SETTINGS_SAVE_USER_INFO_SUCCESS = 'SETTINGS_SAVE_USER_INFO_SUCCESS';
export const SETTINGS_SAVE_USER_INFO_FAILURE = 'SETTINGS_SAVE_USER_INFO_FAILURE';
export const SETTINGS_SAVE_USER_INFO_DISMISS_ERROR = 'SETTINGS_SAVE_USER_INFO_DISMISS_ERROR';
