export const PROJECT_FETCH_PROJECT_LIST_BEGIN = 'PROJECT_FETCH_PROJECT_LIST_BEGIN';
export const PROJECT_FETCH_PROJECT_LIST_SUCCESS = 'PROJECT_FETCH_PROJECT_LIST_SUCCESS';
export const PROJECT_FETCH_PROJECT_LIST_FAILURE = 'PROJECT_FETCH_PROJECT_LIST_FAILURE';
export const PROJECT_FETCH_PROJECT_LIST_DISMISS_ERROR = 'PROJECT_FETCH_PROJECT_LIST_DISMISS_ERROR';
export const PROJECT_FETCH_PROJECT_DTL_BEGIN = 'PROJECT_FETCH_PROJECT_DTL_BEGIN';
export const PROJECT_FETCH_PROJECT_DTL_SUCCESS = 'PROJECT_FETCH_PROJECT_DTL_SUCCESS';
export const PROJECT_FETCH_PROJECT_DTL_FAILURE = 'PROJECT_FETCH_PROJECT_DTL_FAILURE';
export const PROJECT_FETCH_PROJECT_DTL_DISMISS_ERROR = 'PROJECT_FETCH_PROJECT_DTL_DISMISS_ERROR';
